- README.md
- garmin/garmin.py
Hi @cyberjunky, I see you just started this but I got interested and added the Garmin Connect endpoint to allow fetching heart rate data.  (I intend to write some heart rate analysis functions as part of a different project at some point)
> added Garmin Connect heart rate endpoint

- README.md
- garminconnect/__init__.py
This returns a Json similar to:
```
{'totalAverage': {'bodyFatCount': 1, 'physiqueRating': None,
'muscleMass': 99999, 'weight': 99999.99908447266, 'boneMassCount': 1,
'bodyWaterCount': 1, 'visceralFat': None, 'bmiCount': 1, 'until':
1582070399999, 'bodyFat': 99.8700008392334, 'visceralFatCount': 0,
'bodyWater': 59.220001220703125, 'from': 1581984000000,
'muscleMassCount': 1, 'boneMass': 9999, 'metabolicAge': None,
'physiqueRatingCount': 0, 'weightCount': 1, 'bmi': 99.0,
'metabolicAgeCount': 0}, 'startDate': '2020-02-18', 'dateWeightList':
[{'weightDelta': -999.003662109375, 'physiqueRating': None,
'muscleMass': 99999, 'weight': 99999.99908447266, 'timestampGMT':
1582038680000, 'visceralFat': None, 'date': 1582009880000, 'bodyFat':
99.8700008392334, 'samplePk': 1582038680000, 'bodyWater': …
```
> Add Body Composition endpoint

- garminconnect/__init__.py
So that the causes remain attached to the raised ones.
> Chain connection exceptions

- garminconnect/__init__.py
Add method to retrieve exercise set details for a given activity.
> Add exercise set method

- garminconnect/__init__.py
Hello, I'd like to add these two APIs so later on I can consume in home-assistant when the next alarm is going to ring which comes from the device settings API
> add support for device-settings

- garminconnect/__init__.py
**New APIs**
* get_personal_record
* get_device_last_used
* get_activity_splits
* get_activity_split_summaries
* get_activity_weather
* get_activity_hr_in_timezones
* get_activity_details
Also some minor cleanup
> New APIs + cleanup

- README.md
- garminconnect/__version__.py
> Update version + README

- README.md
- garminconnect/__init__.py
With a little change to support connect.garmin.cn
> feat: add support for connect.garmin.cn

- garminconnect/__init__.py
Re-adds get_activity_by_date(), which was accidentally removed in b0c5634.
Fixes #67
> Re-add get_activities_by_date()

- garminconnect/__init__.py
Fixed the cookies saving and restoring.
Add clear cookies for re-authenticate
> Fixed session management for login

- .env
- README.md
- garminconnect/__init__.py
Changes:
- Create a custome .env file "to be ignored in version control"
- Fix md lint violations in README.
- Load and read environmental variables from a dotfile within the repo root.
- Code format.
> Load and read env variables in your code instead of hardcoding sensitive data

- setup.py
Noticed while looking at setup.py there was a missing quotation.  Added that.
> Correct minor syntax error in setup.py

- README.md
- example.py
- garminconnect/__init__.py
* Add `get_goals` method to API client (status param can be `"active"`, `"future"`, or `"past"`
* Add all 3 variations to example program
* Fix typos in README and `example.py`
* Remove `json` from `pip install` instruction (`json` is a built-in lib)
> Add Goals API calls

- example.py
- garminconnect/__init__.py
A couple of methods to manage gear. The idea is to use this and the home-assistant integration for switching default gear per activity.
> Add methods and examples for garmin gear management.

- example.py
- garminconnect/__init__.py
I've added a request for the progress summary that Garmin Connect provides. It e.g. shows a accumulations for elevation gain, kilometers, duration or other metrics for a given period.
I've also added an exemplary usage for the request.
> Add request and example for progress summary

- example.py
- garminconnect/__init__.py
```
-------------------- api.get_daily_steps('2023-01-13, 2023-01-20') --------------------
[
{
"calendarDate": "2023-01-13",
"totalSteps": ****,
"totalDistance": ****,
"stepGoal": ****
},
{
"calendarDate": "2023-01-14",
"totalSteps": ****,
"totalDistance": ****,
"stepGoal": ****
},
{
"calendarDate": "2023-01-15",
"totalSteps": ****,
"totalDistance": ****,
"stepGoal": ****
},
{
"calendarDate": "2023-01-16",
"totalSteps": ****,
"totalDistance": ****,
"stepGoal": ****
},
{
"calendarDate": "2023-01-17",
"totalSteps": ****,
"totalDistance": ****,
"stepGoal": ****
},
{
"calendarDate": "2023-01-18",
"totalSteps": ****,
"totalDistance": ****,
"stepGoal": ****
},
{
"calendarDate": "2023-01-19",
"totalSteps": ****,
"totalDistance": ****,
"stepGoal": ****
},
{
"calendarDate": "2023-01-20", …
```
> Add daily step data summary endpoint for date range

- example.py
- garminconnect/__init__.py
```
-------------------- api.get_body_battery('2023-01-18, 2023-01-25') --------------------
[
{
"date": "2023-01-18",
"charged": **,
"drained": **,
"startTimestampGMT": "2023-01-18T05:00:00.0",
"endTimestampGMT": "2023-01-19T05:00:00.0",
"startTimestampLocal": "2023-01-18T00:00:00.0",
"endTimestampLocal": "2023-01-19T00:00:00.0",
"bodyBatteryValuesArray": [
[
1674018000000,
***
],
[
1674034920000,
***
],
[
1674046800000,
***
],
[
1674075420000,
***
],
[
1674075600000,
***
],
[
1674095760000,
***
]
],
"bodyBatteryValueDescriptorDTOList": [
{
"bodyBatteryValueDescriptorIndex": 0,
"bodyBatteryValueDescriptorKey": "timestamp"
},
{
"bodyBatteryValueDescriptorIndex": 1,
"bodyBatteryValueDescriptorKey": "bodyBatteryLevel"
}
]
},
{
"date": "2023-01-19",
"charged": **,
"drained": **, …
```
> Add body battery endpoint

- garminconnect/__init__.py
the garmin_connect_login_url was wrong when is_cn=true, fix it.
> fix garmin connect login url for china site

- garminconnect/__init__.py
Works for a single day and a range of days using a single endpoint (depending on whether you submit one date or multiple dates)
> Issue 146 - adding Hill Score endpoint

- garminconnect/__init__.py
Switching to garth broke the request for `set_gear_default`.
> Fix setting default gear

- garminconnect/__init__.py
Additional documentation for `get_activities`, based on confusion in #201
> Adding type hints for get_activities

- garminconnect/__init__.py
- pyproject.toml
Following up on, https://github.com/cyberjunky/python-garminconnect/issues/220 . A simple addition to get intensity minutes, I've been using this and has been working well for me. Unfortunately I cannot figure out how to add the test and I can't share creds.
It would be nice to have this in the main branch. Thanks!
> Add intensity minutes

- garminconnect/__init__.py
support deleting blood pressure measurement
> add delete_blood_pressure

- garminconnect/__init__.py
This returns details about users display format settings which are not all included in _get_user_profile()_
> add get_userprofile_settings

- garminconnect/__init__.py
Fixes https://github.com/cyberjunky/home-assistant-garmin_connect/issues/85
> Increase connection pool size
