cyberjunky/python-garminconnect

README.md
garminconnect/__init__.py

Added a quick API to download the activity files in tcx/gpx/fit format.
Snagged the up to date URLs from [this](https://github.com/kjkjava/garmin-connect-export/pull/30/commits/737a5b92c461317516f4d5e696629d9e1af07429) PR on a similar project that didn't meet my needs.
Test Plan:
```
activities = client.get_activities(0, 1)
for activity in activities:
activity_id = activity["activityId"]
tcx_data = client.download_activity(activity_id, dl_fmt=client.ActivityDownloadFormat.GPX)
output_file = f"./{str(activity_id)}.gpx"
with open(output_file, "wb") as fb:
fb.write(tcx_data)
tcx_data = client.download_activity(activity_id, dl_fmt=client.ActivityDownloadFormat.TCX)
output_file = f"./{str(activity_id)}.tcx"
with open(output_file, "wb") as fb:
fb.write(tcx_data)
tcx_data = …
```

Adds download activity API

---

garminconnect/__init__.py

Avoids masking the desired HTTP level error with a possible JSON decode
error. As a side effect, also avoids decoding all response JSONs
multiple times.

Don't try to decode error response JSONs

---

README.md
garminconnect/__init__.py

Currently the library support only getting the user summary.
With this PR, we will be able to fetch also the steps and activity level by 15 minutes.
`[{'startGMT': '2020-07-08T07:00:00.0', 'endGMT': '2020-07-08T07:15:00.0', 'steps': 9, 'primaryActivityLevel': 'sedentary', 'activityLevelConstant': True}, {'startGMT': '2020-07-08T07:15:00.0', 'endGMT': '2020-07-08T07:30:00.0', 'steps': 51, 'primaryActivityLevel': 'sedentary', 'activityLevelConstant': True}]`

Add full steps data

---

garminconnect/__init__.py

This method comes in handy when you want to search for specific activities between specific dates of a specific type.
The method mimics the way how the web interface works fetching 20 activities at a time and automatically loading more on scroll. Particularly useful when you want to search for a long date range (like an entire year).
Usage:
activities = client.get_activities_by_date('2020-12-01', '2020-12-31')
or 
activities = client.get_activities_by_date('2020-12-01', '2020-12-31', 'cycling')

Adding get_activities_by_date method

---

garminconnect/__init__.py

This PR addresses #34: enable the possibility for a different start and end date for get body composition.
I have enabled backwards compatibility to avoid any breaking changes with original function.

Add possibility for a wider start / end range to get body composition

---

garminconnect/__init__.py

This PR is to address issue #59 that I have experienced. 
Given that I am not aware of how widespread this issue is, I have updated the parse_json function to include the regex that was suggested by @mcshosho while still retaining the original one as an alternative.

Fix: Add an extra regex expression to account for updated profile info response

---

garminconnect/__init__.py

Thanks for creating this package!  Not sure if there is a better way but seems like the session code introduced in the last pull request checks if `self.session` is `None`, but perhaps should be checking if `self.session_data` is `None` (since `session` is instantiated in the `Garmin` class on line 191 [here](https://github.com/cyberjunky/python-garminconnect/blob/master/garminconnect/__init__.py#L191)) but doesn't contain anything from what I can tell.  This quick fix seems to fix things.  A better fix might be only instantiate a session if `session_data` is actually passed to the class.
Really cool that this package works so well!

change session check to session_data check in login method

---

garminconnect/__init__.py

Hi, and thank you for this project! I love it!
This lonely `print` statement bugged me a bit, and it is the only `print` statement in the project, as far as I can tell. It breaks the flow of my logs a little, so I'd like it to become a `logger.debug()` statement.

Fix print statement, change to logger.debug()

---

example.py
garminconnect/__init__.py

Hey!
I have been trying to setup this integration for quite some time, now I finally got the time to look at it and I managed to find out what was the issue.
---
After applying my credentials and when the integration tries to startup but then I got this error _(then it loops until Garmin blocks all requests)_
```
Logger: custom_components.garmin_connect
Source: custom_components/garmin_connect/__init__.py:99
Integration: Garmin Connect ([documentation](https://github.com/cyberjunky/home-assistant-garmin_connect), [issues](https://github.com/cyberjunky/home-assistant-garmin_connect/issues))
First occurred: 08:24:11 (17 occurrences)
Last logged: 10:19:32
Unexpected error fetching garmin_connect data: 'NoneType' object is not iterable
Traceback (most recent call last):
File …
```

Error on startup when account has devices without alarm support

---

README.md
example.py

% [`codespell`](https://pypi.org/project/codespell/)
```
./README.md:450: choosen ==> chosen
./example.py:441: choosen ==> chosen
```

Fix typos discovered by codespell

---

garminconnect/__init__.py

Related to https://github.com/cyberjunky/python-garminconnect/issues/117 which I just opened -- `garmin.get_hrv_data()` has a last line of 
`        return self.modern_rest_client.get(url).text #.json()` 
instead of
`        return self.modern_rest_client.get(url).json()`

Replace .text with .json() in garmin.get_hrv_data()

---

example.py
garminconnect/__init__.py

Adds a get_blood_pressure function that calls a newly added blood pressure URL and returns blood pressure summaries and detailed measurements for each day.
There may be a better way to get an individual day, but as this works with a single date, it's fine.
Days without blood pressure measurements do not appear in the data.
```python
-------------------- api.get_blood_pressure('2023-01-19, 2023-01-26') --------------------
{
'from': '2023-01-19',
'until': '2023-01-26',
'measurementSummaries':
[
{
'startDate': '2023-01-26',
'endDate': '2023-01-26',
'highSystolic': 119,
'highDiastolic': 72,
'lowSystolic': 118,
'lowDiastolic': 71,
'numOfMeasurements': 3,
'category': 'NORMAL',
'measurements':
[
{'version': ****,
'systolic': **,
'diastolic': **,
'pulse': None,
'multiMeasurement': False, …
```

Add blood pressure endpoint and function

---

example.py
garminconnect/__init__.py

Adds a function to get the details of floors ascended / descended for a day.
I found the graph on https://connect.garmin.com/modern/daily-summary/2023-01-29, and did not find a way to get more than a day at a time
Response from the API (this wasn't a very active day ...)
```
-------------------- api.get_floors_data('2023-01-29') --------------------
{
"startTimestampGMT": "2023-01-28T23:00:00.0",
"endTimestampGMT": "2023-01-29T07:38:00.0",
"startTimestampLocal": "2023-01-29T00:00:00.0",
"endTimestampLocal": "2023-01-29T08:38:00.0",
"floorsValueDescriptorDTOList": [
{
"key": "startTimeGMT",
"index": 0
},
{
"key": "endTimeGMT",
"index": 1
},
{
"key": "floorsAscended",
"index": 2
},
{
"key": "floorsDescended",
"index": 3
}
],
"floorValuesArray": [
[
"2023-01-28T23:00:00.0", …
```

Add floors endpoint, function, and example

---

garminconnect/__init__.py

Add method to retrieve information about "virtual" challenges.
These challenges don't have a start/end date.
In the app, they are called "expeditions".

Add get_inprogress_virtual_challenges method

---

garminconnect/__init__.py

Works for a single day and a range of days using a single endpoint (depending on whether you submit one date or multiple dates)
Returns the endurance score value for a single day, including classifications, or returns the aggregated weekly values for a range of weeks (specified using days)

Add endurance score endpoint

---

garminconnect/__init__.py

Race predictions endpoint for runners.  Takes zero or three parameters and returns the time predictions for a 5k, 10k, Half, and Full marathon.
Someone should test this, since it appears you need to include your display name in the endpoint (which I tried to do via using the display name property of the garmin class), but I want to be sure it works for others as well

Race Predictions

---

garminconnect/__init__.py

Provides the ability to set a blood pressure data
```yaml
from getpass import getpass
import garminconnect
email = input("Enter email address: ")
password = getpass("Enter password: ")
garmin = garminconnect.Garmin(email, password)
garmin.login()
// passing a timestamp
In [4]: garmin.set_blood_pressure(112,72,72,timestamp="2023-10-16T23:10:15")
Out[4]: <Response [200]>
// using `datetime.now()`
In [5]: garmin.set_blood_pressure(113,73,73)
Out[5]: <Response [200]>
// passing notes
In [6]: garmin.set_blood_pressure(114,74,74,notes="testing via api")
Out[6]: <Response [200]>
```
Fixes: https://github.com/cyberjunky/python-garminconnect/issues/167

Introduces ability to add blood pressure

---

garminconnect/__init__.py

Replacing `def get_device_alarms(self) -> List[str, Any]:` with `def get_device_alarms(self) -> Dict[str, Any]:`
Closes #177

Fix get_device_alarms

---

.gitignore
example.py
garminconnect/__init__.py

Added one endpoint and renamed another. Also updated .gitignore
- Renamed `get_activity_evaluation` to `get_activity` and updated docstring/logger, because this returns all activity summary, not just the evaluation. Also updated example.py
- Added `delete_activity`, which accepts an activity id, and deletes that activity from Garmin Connect
- Updated the .gitignore file to add `ignore/` and `.idea/`. Adding `ignore/` allows for easy local testing in a confined folder without having to worry about accidentally committing extra files. `.idea/` is an automatically generated PyCharm folder, if you use PyCharm

Get and Delete Activities by ID

---

garminconnect/__init__.py

Issue https://github.com/cyberjunky/python-garminconnect/issues/190
Adding endpoint for device solar data.
I limited the return values to just the specific solar data `deviceSolarInput` because it's already a lot of data, and I suspect we already return all the other data from the device settings endpoint
If the device has no solar data, it returns the following value (I tested with my non solar 945):
`{'solarDailyDataDTOs': []}`
With solar data, it returns something like the following
```python
{
"solarDailyDataDTOs": 
[ # List with one entry per day
{
"localConnectDate": "2024-03-10",
"userProfilePk": 71328280,
"deviceId": 3424284515,
"solarInputReadings": [
{
"readingTimestampLocal": "2024-03-10T00:01:00.0",
"readingTimestampGmt": "2024-03-10T05:01:00.0",
"solarUtilization": 0.0, …
```

Adding device solar data endpoint

---

garminconnect/__init__.py

[Issue 134](https://github.com/cyberjunky/python-garminconnect/issues/134)
Three endpoints
`get_menstrual_data_for_date` which takes a single date and returns the Garmin Menstrual Summary data for that date
`get_menstrual_calendar_data` which takes two dates and returns summaries of cycles that have days between the two days
`get_pregnancy_summary`, which takes no arguments and returns a snapshot of pregnancy data

Womens Health API Endpoints

---

garminconnect/__init__.py

[Issue 196](https://github.com/cyberjunky/python-garminconnect/issues/196).  Looks like the names of the timestamps in the add weigh in payload changed. 
It's possible there are other areas this might need to be changed to.
I get a 400 with the original names, but a 204 now

Bugfix Issue #196

---

example.py
garminconnect/__init__.py

Returns primary training device info, as well as a list of all devices.  We could adjust it slightly if we wanted to minimize the return data to just Primary Training Device info, but I'm not sure if that's necessary.
That would look like...
```python
...
response = self.connectapi(url)
del response['RegisteredDevices']
return response 
```
Return data looks like:
```python
{'PrimaryTrainingDevice': {'deviceId': XXX},
'WearableDevices': {'deviceWeights': [{'displayName': 'Forerunner 955 Solar',
'deviceId': XXX,
'imageUrl': 'https://s3.amazonaws.com/garmin-connect-prod/profile_images/98d07f81-3a9f-4d5a-9172-45c6c3080d36-71.png',
'weight': 3,
'primaryTrainingCapable': True,
'lhaBackupCapable': True,
'primaryWearableDevice': True},
{'displayName': 'Forerunner 945',
'deviceId': XXX, …
```

Adding endpoint for getting primary training device information

---

README.md
example.py
garminconnect/__init__.py

Asked for in https://github.com/cyberjunky/python-garminconnect/issues/204
Added to example.py and readme as well
Tested on my own and works with both dates, no dates, only cdate, and only timestamp.
It doesn't appear that the dates are actually used for anything in Garmin connect, but maybe they will be eventually.
This endpoint does not require that the date and timestamp be on the same day

Add endpoint for adding hydration data

---

example.py
garminconnect/__init__.py

Retrieves the following stats (fake values) from `https://connect.garmin.com/fitnessage-service/fitnessage/[date]`:
```
{
"chronologicalAge": 20,
"fitnessAge": 18.315871748264364,
"achievableFitnessAge": 19.38654477840031,
"previousFitnessAge": 18.315871748264364,
"components": {
"vigorousDaysAvg": {
"value": 2.5,
"stale": false,
"numOfWeeksForIm": 4
},
"rhr": {
"value": 52,
"stale": false
},
"vigorousMinutesAvg": {
"value": 104.5,
"stale": false,
"numOfWeeksForIm": 4
},
"bmi": {
"value": 20.0,
"stale": false,
"lastMeasurementDate": "2024-06-19"
}
},
"lastUpdated": "2024-06-22T00:00:00.0"
}
```

Extend API to retrieve fitness age data

---

garminconnect/__init__.py

This PR makes the following changes:
1. Added 'groupbyactivities' parameter to get_progress_summary_between_dates()
- Allows control over grouping by activity type
- Defaults to True for backwards compatibility
2. Updated type annotations:
- get_devices() now returns List[Dict[str, Any]]
- get_device_alarms() returns List[Any]
- cdate in add_hydration_data() is now explicitly Optional
3. Minor code cleanup:
- Reorganized imports
- Adjusted some function signatures
Tested:
- get_progress_summary_between_dates with groupbyactivities=False
- make format/lint/codespell
Please review and provide feedback.

Add grouping option to progress summary and fix type annotations

---

README.md
example.py
garminconnect/__init__.py

Adds two endpoints.
First, a body battery daily events endpoint, which includes:
- Naps
- Autodetected activities like walks
- All activities (in a summary form)
For each of these, it includes the body battery impact information
I believe this endpoint is used to populate the Body Battery graph 
Second, a wellness daily events endpoint, which includes highly summarized info for all recorded and auto-detected activities

Daily Events Endpoints

---

garminconnect/__init__.py

This is useful to do cumulative sums of time (not provided in Garmin Connect web site), distance (provided in Garmin Connect web site), etc. 
As an example, it comes in handy to keep track of, e.g., battery life of power meters, or any other gear where tracking time instead of distance is desired.
This was inspired by this [post on reddit](https://www.reddit.com/r/Garmin/comments/b3czi7/hours_vs_distance/ej0nna3/), which no longer works.
The example below takes some code from the code snipped in said post to cumulative sum the total time a piece of gear has been used by adding up the time of all activities where said gear is set/assigned to.
Cheers!
```python
#!/usr/bin/env python3
"""
pip3 install garth requests readchar
export EMAIL=<your garmin email>
export PASSWORD=<your garmin …
```

Add endpoint to list activities where certain gear is used. 

---

garminconnect/__init__.py

Small additions to the API
- method to change type of an existing activity
- method to create activity from JSON
- method to create activity from basic parameters
- added a parameter to get_activities_by_date to allow specifying in which order activities should be returned
I needed these for my project but thought they might be useful for others too.

Small additions to activity API

---

garminconnect/__init__.py

Use it like this:
local_timestamp = weigh_in_date.strftime('%Y-%m-%dT%H:%M:%S') gmt_timestamp = weigh_in_date.astimezone(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S')
client.add_weigh_in_with_timestamps(
weight=weight,
unitKey=unit,
dateTimestamp=local_timestamp,
gmtTimestamp=gmt_timestamp
)
needs:
from datetime import datetime, timezone

added method: add_weigh_in_with_timestamps()

---

example.py

This PR modifies the switch function for option 'p' in example.py to address an issue with non-unique filenames when downloading multiple activities in batch.
Previously, the file naming convention for downloaded activities resulted in non-unique filenames. For example, if multiple activities were recorded in "New York" and labeled "New_York_Running", the files would overwrite each other, making it difficult to batch download activities.
I modified the file naming convention by including a unique identifier (such as activity_id and startTimeLocal) in the filename. This ensures that filenames are unique for each downloaded activity, even if the activity names are the same.
Users can now easily scrape and download all activities by adjusting the start date and limit variables without the …

Fix activity filename overwrite issue in batch downloads (option 'p')

---

garminconnect/__init__.py

This reverts commit 663bdd7545b680b58994b91fcf043efd459a263a.
I identified the issue incorrectly and we should revert my change.
The root cause of #253 appears to be that Garmin simply doesn't have Max Metrics for that day yet. I believe until you've done an activity on that day, there are no Max Metrics values
The code as it currently stands only returns the current day, regardless of the date entered

Revert "#253 - Updating Max Metrics URL"
